---
- hosts: icx
  #gather_facts: no
  vars:
    ansible_network_os: icx
    ansible_user: lab
    ansible_become: True
    ansible_password: lab123
    ansible_become_method: enable
    ansible_become_pass: lab123
    ansible_command_timeout: 60

  tasks:
  # - name: upload primary flash to the remote scp server
  #   icx_copy:
  #     upload: flash_primary
  #     protocol: scp
  #     remote_server: 172.16.10.49
  #     remote_filename: primary.bin
  #     remote_user: lab
  #     remote_pass: lab123

  # - name: download primary flash from the remote scp server
  #   icx_copy:
  #     download: flash_primary
  #     protocol: scp
  #     remote_server: 172.16.10.49
  #     remote_filename: SPS08080b.bin
  #     remote_user: lab
  #     remote_pass: lab123

  # - name: upload running-config to the remote scp server
  #   icx_copy:
  #     upload: running-config
  #     protocol: scp
  #     remote_server: 172.16.10.49
  #     remote_filename: running.conf
  #     remote_user: "{{ scp_remote_user }}"
  #     remote_pass: "{{ scp_remote_pass }}"

  # - name: download running-config from the remote scp server
  #   icx_copy:
  #     download: running-config
  #     protocol: scp
  #     remote_server: 172.16.10.49
  #     remote_filename: running.conf
  #     remote_user: lab
  #     remote_pass: lab123


  # - name: upload startup-config to the remote scp server
  #   icx_copy:
  #     upload: running-config
  #     protocol: scp
  #     remote_server: 172.16.10.49
  #     remote_filename: startup.conf
  #     remote_user: lab
  #     remote_pass: lab123

  # - name: download startup-config from the remote scp server
  #   icx_copy:
  #     download: running-config
  #     protocol: scp
  #     remote_server: 172.16.10.49
  #     remote_filename: startup.conf
  #     remote_user: lab
  #     remote_pass: lab123

  # HTTPS

  # - name: download startup-config from the remote https server
  #   icx_copy:
  #     download: startup-config
  #     protocol: https
  #     remote_server: fileserver.lab.in
  #     remote_filename: startup.conf

  # - name: download primary flash from the remote https server
  #   icx_copy:
  #     download: flash_primary
  #     protocol: https
  #     remote_server: fileserver.lab.in
  #     remote_filename: filestorage/test/SPS08080b.bin


  # - name: download secondary flash from the remote https server
  #   icx_copy:
  #     download: flash_primary
  #     protocol: https
  #     remote_server: fileserver.lab.in
  #     remote_filename: filestorage/test/SPS08080b.bin

#copy https flash fileserver.lab.in /filestorage/test/SPS08080b.bin primary
